### PR TITLE
Feature/update css

### PR DESCRIPTION
**Pull request by kambayashia**
improve this PR
https://github.com/Ranks/emojify.js/pull/133

- update dependency package
 - gulp-image-data-uri
   - datauri
- update dist/css/data-uri/

### CODE REVIEW

**Comment by kambayashia** [comment]
why do you not merge this?

**Comment by hassankhan** [comment]
I've recently transferred the repo to Ranks and lost my write access in the process. I'll ping them and try and get this merged :)

**Comment by kambayashia** [comment]
thank you :bow:

**Comment by kambayashia** [comment]
:joy_cat:

**Comment by hassankhan** [comment]
Thanks for the PR! :+1:

**Pull request merged**
